GET http://localhost:8080/hello
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmb28iLCJleHAiOjE1NzI5MjkwMjUsImlhdCI6MTU3Mjg5MzAyNX0.yQLTXrJDhB7Bbmvv6hG1Op89-TaSSU0XzyCZfCD7pgk


###